version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels:
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    labels:
      - dependencies
    groups:
      python-deps:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
