name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'breaking'
      - 'major'
  minor:
    labels:
      - 'enhancement'
      - 'feature'
      - 'minor'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'patch'

categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking'
      - 'major'
  - title: 'Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Removals and Deprecations'
    labels:
      - 'removal'
  - title: 'Performance'
    labels:
      - 'performance'
  - title: 'Testing'
    labels:
      - 'testing'
  - title: 'Continuous Integration'
    labels:
      - 'ci'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: 'Refactoring'
    labels:
      - 'refactoring'
  - title: 'Style'
    labels:
      - 'style'
  - title: 'Dependencies'
    labels:
      - 'dependencies'
      - 'build'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-template: '$MAJOR.$MINOR.$PATCH'

autolabeler:
  - label: 'enhancement'
    branch:
      - '/^feat/'
  - label: 'bug'
    branch:
      - '/^fix/'
      - '/^bug/'
  - label: 'documentation'
    branch:
      - '/^docs/'

template: |
  ## Changes

  $CHANGES
