name: Linting

on:
  push:
    branches:
      - master
      - staging
  pull_request:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      update_coverage_badge: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]' }}
